languageCode = "en"
languageName = "English"
weight = 1
title = "SeesDisease"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "SeesDisease BWKI Dokumentation"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Lorenz Rutkevich"
  image = "img/avatar.png"
  headline = "This is my website with my links"
  bio = "A little bit about you"
   links = [
     { link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/nunocoracao/blowfish" },
     { x-twitter = "https://twitter.com/burufugu" }
   ]
